// src/vue/base.vue
<script>
import { booleanProp, defineStringProp, intProp, stringProp } from "./props";
import {
    computeAlt,
    computeData,
    computePlaceholderStyle,
    computeStyle,
    computeWrapperClass,
    computeWrapperStyle,
} from "../_/compute";
import { createPlaceholderHandler } from "../_/placeholder";
import {
    parseAlt,
    parseAnchor,
    parseBot,
    parseFocus,
    parseMode,
    parsePlaceholder,
    parsePosition,
    parsePreTransform,
    parseRatio,
    parseSrc,
    parseStep,
    parseTransition,
    parseTransitionDelay,
    parseTransitionDuration,
    parseTransitionTimingFunction,
} from "../_/parse";
import { rValidAnchor, rValidMode, rValidPlaceholder, rValidRatio } from "../_/validate";

const rInitialProps = /^(\*+)(.*[^*])(\*+)$/;

const callFactory = ( func, _args, isProp = false ) => {
    const args = _args.map( arg => ( ( typeof arg === `function` ) ? {
        "f": arg,
    } : {
        // eslint-disable-next-line no-nested-ternary
        "s": isProp ?
            `${ arg }` :
            ( rInitialProps.test( `${ arg }` ) ? `${ `${ arg }`.replace( rInitialProps, `$2` ) }` : `p_${ arg }` ),
    } ) );
    return function() {
        // eslint-disable-next-line no-invalid-this
        return func( ...args.map( ( { f, s } ) => ( f ? f( this ) : this[ s ] ) ) );
    };
};

const computed = {};
const props = {};

for ( const [ propName, type, parseMethod, args ] of [
    [ `alt`, stringProp, parseAlt ],
    [ `anchor`, defineStringProp( rValidAnchor ), parseAnchor ],
    [ `bot`, stringProp, parseBot ],
    [ `focus`, stringProp, parseFocus ],
    [ `mode`, defineStringProp( rValidMode ), parseMode ],
    [ `placeholder`, defineStringProp( rValidPlaceholder ), parsePlaceholder, [ `placeholder`, `src` ] ],
    [ `position`, stringProp, parsePosition ],
    [ `preTransform`, stringProp, parsePreTransform ],
    [ `ratio`, defineStringProp( rValidRatio ), parseRatio ],
    [ `src`, stringProp, parseSrc ],
    [ `step`, intProp, parseStep ],
    [ `transition`, booleanProp( null, true ), parseTransition ],
    [ `transitionDelay`, stringProp, parseTransitionDelay ],
    [ `transitionDuration`, stringProp, parseTransitionDuration ],
    [ `transitionTimingFunction`, stringProp, parseTransitionTimingFunction ],
] ) {
    computed[ `p_${ propName }` ] = callFactory( parseMethod, args || [ propName ], true );
    props[ propName ] = type;
}

for ( const [ propName, func, args ] of [
    [ `_alt`, computeAlt, [ `alt`, `src` ] ],
    [ `_dataAttributes`, computeData, [ `anchor`, `bot`, `focus`, `mode`, `preTransform`, `src`, `step` ] ],
    [
        `_style`,
        computeStyle,
        [ `anchor`, `mode`, `position`, `transitionDelay`, `transitionDuration`, `transitionTimingFunction` ],
    ],
    [
        `_placeholderStyle`,
        computePlaceholderStyle,
        [
            `anchor`,
            `focus`,
            `mode`,
            `placeholder`,
            `position`,
            `preTransform`,
            `ratio`,
            `src`,
            `transition`,
            c => c._p.setData,
        ],
    ],
    [ `_wrapperClass`, computeWrapperClass, [ `src`, `transition` ] ],
    [ `_wrapperStyle`, computeWrapperStyle, [ `ratio` ] ],
] ) {
    computed[ propName ] = callFactory( func, args );
}

export default {
    props,
    computed,
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    beforeCreate() {
        this._p = createPlaceholderHandler();
    },
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    mounted() {
        this._p.setPlaceholderElement( this.$refs.p );
    },
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    unmounted() {
        this._p.delete();
    },
};
</script>
<template>
    <div class="twic-i">
        <div
            :class="_wrapperClass"
            :style="_wrapperStyle"
        >
            <component
                :is="_is"
                :alt="_alt"
                :style="_style"
                v-bind="{ ..._dataAttributes }"
            />
            <div
                ref="p"
                :style="_placeholderStyle"
            />
        </div>
    </div>
</template>
<style src="../_/style.css"></style>

// src/angular/base.component.ts
/**
 * base component
 * Used in twic-img and twic-video
 */
import {
    Component,
    ElementRef,
    EventEmitter,
    Input,
    Output,
    ViewChild,
} from "@angular/core";

// eslint-disable-next-line no-duplicate-imports
import type {
    OnChanges,
    OnDestroy,
    OnInit,
} from "@angular/core";

import type { Anchor, AnchorObject, Mode, Placeholder, StateEvent, State } from "../_/types";

import {
    computeAlt,
    computeData,
    computePlaceholderStyle,
    computeStyle,
    computeWrapperClass,
    computeWrapperStyle,
} from "../_/compute";

import { Observer } from "../_/Observer";

import {
    parseAlt,
    parseAnchor,
    parseBot,
    parseFocus,
    parseIntrinsic,
    parseMode,
    parseEager,
    parsePlaceholder,
    parsePosition,
    parsePreTransform,
    parseRatio,
    parseSrc,
    parseStep,
    parseTransition,
    parseTransitionDelay,
    parseTransitionDuration,
    parseTransitionTimingFunction,
} from "../_/parse";

@Component( {
    "selector": `lib-twic-base`,
    "template": `<p>To implement in child class</p>`,
    "host": {
        "class": `twic-i twic-d`,
    },
} )
export class TwicBaseComponent implements OnInit, OnDestroy, OnChanges {
    @Input() alt: string = undefined;
    @Input() anchor: Anchor = undefined;
    @Input() bot: string = undefined;
    @Input() class: string = undefined;
    @Input() focus: string = undefined;
    @Input() intrinsic: string = undefined;
    @Input() mode: Mode = undefined;
    @Input() eager: boolean | string;
    @Input() placeholder: Placeholder = undefined;
    @Input() position: string = undefined;
    @Input() preTransform: string = undefined;
    @Input() ratio: number | string = undefined;
    @Input() src: string;
    @Input() step: number = undefined;
    @Input() transition:boolean | string;
    @Input() transitionDelay: string = undefined;
    @Input() transitionDuration: string = undefined;
    @Input() transitionTimingFunction: string = undefined;
    @Output() stateChangeEvent = new EventEmitter< StateEvent >();
    _alt: string = undefined;
    _anchor: AnchorObject = undefined;
    _bot: string = undefined;
    _eager: boolean;
    _focus: string = undefined;
    _intrinsic: string = undefined;
    _mode: Mode = undefined;
    _placeholder: Placeholder = undefined;
    _position: string = undefined;
    _preTransform: string = undefined;
    _ratio: number = undefined;
    _src: string;
    _step: number = undefined;
    _transition:Record< string, boolean >;
    _transitionDelay: string = undefined;
    _transitionDuration: string = undefined;
    _transitionTimingFunct: string = undefined;
    @ViewChild( `media`, {
        "static": true,
    } ) mediaRef!: ElementRef;
    description: string;
    mediaAttributs: Record<string, string>;
    mediaStyle: Record<string, string>;
    observer: Observer;
    placeholderStyle: Record<string, string>;
    wrapperClass: string;
    wrapperStyle: Record<string, string>;
    constructor() {
        this.observer = new Observer( ( state: State ) => {
            this.stateChangeEvent.emit( {
                "target": this,
                state,
            } );
        } );
    }
    ngOnInit(): void {
        this.observer.setMedia(
            this.mediaRef?.nativeElement || undefined
        );
    }
    ngOnChanges( ): void {
        this._alt = parseAlt( this.alt );
        this._anchor = parseAnchor( this.anchor );
        this._bot = parseBot( this.bot );
        this._focus = parseFocus( this.focus );
        this._intrinsic = parseIntrinsic( this.intrinsic );
        this._mode = parseMode( this.mode );
        this._eager = parseEager( this.eager );
        this._placeholder = parsePlaceholder( this.placeholder, this.src );
        this._position = parsePosition( this.position );
        this._preTransform = parsePreTransform( this.preTransform );
        this._ratio = parseRatio( this.ratio );
        this._src = parseSrc( this.src );
        this._step = parseStep( this.step );
        this._transition = parseTransition( this.transition );
        this._transitionDelay = parseTransitionDelay( this.transitionDelay );
        this._transitionDuration = parseTransitionDuration( this.transitionDuration );
        this._transitionTimingFunct = parseTransitionTimingFunction( this.transitionTimingFunction );

        this.description = computeAlt( this._alt, this._src );

        this.mediaAttributs = {
            ...computeData(
                this._anchor,
                this._bot,
                this._eager,
                this._focus,
                this._intrinsic,
                this._mode,
                this._preTransform,
                this._src,
                this._step
            ),
        };

        this.mediaStyle = computeStyle(
            this._anchor,
            this._mode,
            this._position,
            this._transitionDelay,
            this._transitionDuration,
            this._transitionTimingFunct
        );

        this.placeholderStyle = computePlaceholderStyle(
            this._anchor,
            this._focus,
            this._mode,
            this._placeholder,
            this._position,
            this._preTransform,
            this._ratio,
            this._src,
            this._transition,
            this._transitionDelay,
            this._transitionDuration,
            this._transitionTimingFunct,
            this.observer.setPlaceholderData
        );

        this.wrapperClass = computeWrapperClass( this.src, this._transition );

        this.wrapperStyle = computeWrapperStyle( this._ratio );
    }
    ngOnDestroy(): void {
        this.observer.destroy();
    }
}
