// src/vue/TwicMedia.vue
<script>
import {
    computeAlt,
    computeData,
    computePlaceholderStyle,
    computeStyle,
    computeWrapperClass,
    computeWrapperStyle,
} from "../_/compute";
import { Observer } from "../_/Observer";
import {
    parseAlt,
    parseAnchor,
    parseBot,
    parseFocus,
    parseIntrinsic,
    parseMediaTag,
    parseMode,
    parseEager,
    parsePlaceholder,
    parsePosition,
    parsePreTransform,
    parseRatio,
    parseSrc,
    parseStep,
    parseTitle,
    parseTransition,
    parseTransitionDelay,
    parseTransitionDuration,
    parseTransitionTimingFunction,
} from "../_/parse";
import { preComputePlaceholder } from "../_/preCompute";
import { rValidAnchor, rValidIntrinsic, rValidMode, rValidPlaceholder, rValidRatio } from "../_/validate";
import { booleanProp, defineStringProp, intProp, stringProp, videoOptionsProps } from "./props";
import { callFactory } from "./utils";

const computed = {};
const props = {};
const emits = [ `stateChange` ];

for ( const [ propName, type, parseMethod ] of [
    [ `alt`, stringProp, parseAlt ],
    [ `anchor`, defineStringProp( rValidAnchor ), parseAnchor ],
    [ `bot`, stringProp, parseBot ],
    [ `focus`, stringProp, parseFocus ],
    [ `intrinsic`, defineStringProp( rValidIntrinsic ), parseIntrinsic ],
    [ `mediaTag`, stringProp, parseMediaTag ],
    [ `mode`, defineStringProp( rValidMode ), parseMode ],
    [ `eager`, booleanProp( null, false ), parseEager ],
    [ `placeholder`, defineStringProp( rValidPlaceholder ), parsePlaceholder ],
    [ `position`, stringProp, parsePosition ],
    [ `preTransform`, stringProp, parsePreTransform ],
    [ `ratio`, defineStringProp( rValidRatio ), parseRatio ],
    [ `src`, stringProp, parseSrc ],
    [ `step`, intProp, parseStep ],
    [ `title`, stringProp, parseTitle ],
    [ `transition`, booleanProp( null, true ), parseTransition ],
    [ `transitionDelay`, stringProp, parseTransitionDelay ],
    [ `transitionDuration`, stringProp, parseTransitionDuration ],
    [ `transitionTimingFunction`, stringProp, parseTransitionTimingFunction ],
    [ `videoOptions`, videoOptionsProps, v => v ],
] ) {
    computed[ `p_${ propName }` ] = callFactory( parseMethod, [ `*${ propName }*` ] );
    props[ propName ] = type;
}
computed[ `p_undefined` ] = () => undefined;

for ( const [ propName, func, args ] of [
    [ `_alt`, computeAlt, [ `alt`, `mediaTag`, `src` ] ],
    [
        `_dataAttributes`,
        computeData,
        [
            `anchor`,
            `bot`,
            `eager`,
            `focus`,
            `intrinsic`,
            `mediaTag`,
            `mode`,
            `preTransform`,
            `src`,
            `step`,
            `videoOptions`,
        ],
    ],
    [
        `_style`,
        computeStyle,
        [
            `anchor`,
            `mediaTag`,
            `mode`,
            `position`,
            `transitionDelay`,
            `transitionDuration`,
            `transitionTimingFunction`,
        ],
    ],
    [
        `_placeholderStyle`,
        computePlaceholderStyle,
        [
            `anchor`,
            `focus`,
            `mode`,
            `placeholder_`,
            `position`,
            `preTransform`,
            `ratio`,
            `src`,
            `transition`,
            `transitionDelay`,
            `transitionDuration`,
            `transitionTimingFunction`,
            `videoOptions`,
            c => c.observer.setPlaceholderData,
        ],
    ],
    [
        `p_placeholder_`,
        preComputePlaceholder,
        [
            `placeholder`,
            `src`,
        ],
    ],
    [ `_wrapperClass`, computeWrapperClass, [ `undefined`, `src`, `transition` ] ],
    [ `_wrapperStyle`, computeWrapperStyle, [ `ratio` ] ],
] ) {
    computed[ propName ] = callFactory( func, args );
}

export default {
    props,
    emits,
    computed,
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    beforeCreate() {
        this.observer = new Observer( state => {
            this.$emit( `stateChange`, {
                state,
            } );
        } );
    },
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    mounted() {
        this.observer.setMedia( this.$refs.media );
    },
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    unmounted() {
        this.observer.destroy();
    },
};
</script>
<template>
    <div
        :class="_wrapperClass"
        :style="_wrapperStyle"
        :title="p_title"
    >
        <component
            :is="p_mediaTag"
            ref="media"
            :alt="p_mediaTag === `img` ? _alt : undefined"
            :style="_style"
            v-bind="{ ..._dataAttributes }"
        />
        <div
            v-if="p_placeholder_"
            :style="_placeholderStyle"
        />
    </div>
</template>
<style src="../_/style.css"></style>

// src/svelte3/TwicMedia.svelte
<svelte:options tag="twic-media" />
<script context="module" lang="ts">
/* eslint-disable no-duplicate-imports */
/* eslint-disable no-unused-vars */
/* eslint-disable @typescript-eslint/no-unused-vars */
import {
    parseClassName,
    parseMediaTag,
    type Anchor,
    type Mode,
    type Placeholder,
    type State,
    type VideoOptions,
} from "./_utils.js";
import {
    computeAlt,
    computeData,
    computePlaceholderStyle,
    computeStyle,
    computeWrapperClass,
    computeWrapperStyle,
    isBrowser,
    Observer,
    parseAlt,
    parseAnchor,
    parseBot,
    parseFocus,
    parseIntrinsic,
    parseMode,
    parseEager,
    parsePlaceholder,
    parsePosition,
    parsePreTransform,
    parseRatio,
    parseSrc,
    parseStep,
    parseTitle,
    parseTransition,
    parseTransitionDelay,
    parseTransitionDuration,
    parseTransitionTimingFunction,
    preComputePlaceholder,
    styleToString,
} from "./_utils.js";
/* eslint-disable-next-line camelcase */
import { createEventDispatcher, onDestroy, onMount } from "svelte/internal";
</script>

<script lang="ts">
export let alt: string = undefined;
export let anchor: Anchor = undefined;
export let bot: string = undefined;
let className: string = undefined;
export { className as class };
export let focus: string = undefined;
export let intrinsic: string = undefined;
export let media: HTMLElement= undefined;
export let mediaTag: string = `img`;
export let mode: Mode = undefined;
export let eager: boolean = false;
export let placeholder: Placeholder = undefined;
export let position: string = undefined;
export let preTransform: string = undefined;
export let ratio: number | string = undefined;
export let src: string;
export let step: number | string = undefined;
export let state: State = undefined;
export let title: string = undefined;
export let transition: boolean | string = undefined;
export let transitionDelay: string = undefined;
export let transitionDuration: string = undefined;
export let transitionTimingFunction: string = undefined;
export let videoOptions: VideoOptions = undefined;

const observer = new Observer( ( _state: State )=> {
    state = _state;
} );

const stateDispatcher = createEventDispatcher();
$: stateDispatcher( `statechange`, { state } );

$: parsedAlt = parseAlt( alt );
$: parsedAnchor = parseAnchor( anchor );
$: parsedBot = parseBot( bot );
$: parsedClassName = parseClassName( className ) || ``;
$: parsedEager = parseEager( eager );
$: parsedFocus = parseFocus( focus );
$: parsedIntrinsic = parseIntrinsic( intrinsic );
$: parsedMediaTag = parseMediaTag( mediaTag );
$: parsedMode = parseMode( mode );
$: parsedPlaceholder = parsePlaceholder( placeholder );
$: parsedPosition = parsePosition( position );
$: parsedPreTransform = parsePreTransform( preTransform );
$: parsedRatio = parseRatio( ratio );
$: parsedSrc = parseSrc( src );
$: parsedStep = parseStep( step );
$: parsedTitle = parseTitle( title );
$: parsedTransition = parseTransition( transition );
$: parsedTransitionDelay = parseTransitionDelay( transitionDelay );
$: parsedTransitionDuration = parseTransitionDuration( transitionDuration );
$: parsedTransitionTimingFunction = parseTransitionTimingFunction( transitionTimingFunction );
$: parsedVideoOptions = videoOptions;

$: placeholder_ = preComputePlaceholder( parsedPlaceholder, parsedSrc );

$: _alt = computeAlt( parsedAlt, parsedMediaTag, parsedSrc );
$: _data = computeData(
    parsedAnchor,
    parsedBot,
    parsedEager,
    parsedFocus,
    parsedIntrinsic,
    parsedMediaTag,
    parsedMode,
    parsedPreTransform,
    parsedSrc,
    parsedStep,
    parsedVideoOptions,
);
$: _placeholderStyle = styleToString( computePlaceholderStyle(
    parsedAnchor,
    parsedFocus,
    parsedMode,
    placeholder_,
    parsedPosition,
    parsedPreTransform,
    parsedRatio,
    parsedSrc,
    parsedTransition,
    parsedTransitionDelay,
    parsedTransitionDuration,
    parsedTransitionTimingFunction,
    parsedVideoOptions,
    observer.setPlaceholderData,
) );

$: _style = styleToString( computeStyle(
    parsedAnchor,
    parsedMediaTag,
    parsedMode,
    parsedPosition,
    parsedTransitionDelay,
    parsedTransitionDuration,
    parsedTransitionTimingFunction
) );
$: _wrapperStyle = styleToString( computeWrapperStyle( parsedRatio ) );

if ( isBrowser ) {
    onMount( () => {
        observer.setMedia( media );
    } );
    onDestroy( () => {
        observer.destroy();
    } );
}
</script>
<div
    class = { computeWrapperClass( parsedClassName, src, parsedTransition ) }
    style = { _wrapperStyle }
    title = { parsedTitle }
>
    <svelte:element this={ mediaTag }
        bind:this = { media }
        alt = { _alt }
        style = { _style }
        { ..._data }
    ></svelte:element>
    {#if placeholder_ }
        <div style = { _placeholderStyle } />
    {/if}
</div>
