// src/react/TwicImg.tsx
import React, { useEffect, useRef } from "react";
import { computeMagnifierStyle } from "../_/compute";
import initMagnifier from "../_/magnifier";
import { parseClassName, parseZoom } from "../_/parse";
import { boolean, number, oneOfType, string } from "./props";
import TwicMedia from "./TwicMedia";
import type { ImgAttributes } from "./types";
import { splitProperties } from "./utils";

const TwicImg: React.FC< ImgAttributes > = props => {
    const hostElement = useRef< HTMLDivElement >( null );
    const { hostProps, mediaProps } = splitProperties( {
        "role": `img`,
        ...props,
    } );
    useEffect(
        () => {
            if ( parseZoom( props.zoom ) ) {
                initMagnifier( hostElement.current );
            }
        },
        []
    );
    const className = parseClassName( props.className ) || ``;
    const zoom = parseZoom( props.zoom );
    return (
        <div
            ref={ hostElement }
            { ...hostProps }
            className={ `twic-i ${ className } ${ zoom ? `twic-z` : `` }` }
            style={ {
                ...hostProps.style,
                ...computeMagnifierStyle( zoom ),
            } }
        >
            { zoom && (
                <TwicMedia
                    { ...mediaProps }
                    className="twic-m"
                    mediaTag="div"
                    mode="cover"
                />
            ) }
            <TwicMedia
                { ...mediaProps }
                className=""
                mediaTag="img"
            />
        </div>
    );
};

TwicImg.propTypes = {
    "refit": oneOfType( [ boolean, string ] ),
    "zoom": number,
};
export default TwicImg;

// src/svelte3/TwicImg.svelte
<svelte:options tag={null}/>

<script context="module" lang="ts">
import {
    computeMagnifierStyle,
    getCurrentComponent,
    isBrowser,
    isWebComponents,
    initMagnifier,
    parseClassName,
    parseStyle,
    parseZoom,
    splitProperties,
    styleToString,
    type State,
} from "./_utils.js";
import TwicMedia from "./TwicMedia.svelte";
import { onMount } from "svelte";
</script>
<script lang="ts">
let className: string = undefined;
export { className as class };
export let state: State = undefined;
export let style: string | Record< string, unknown > = {};
export let zoom: number | string = undefined;

let hostElement:HTMLDivElement | any;
let hostProps, mediaProps;

$: ( { hostProps, mediaProps } = splitProperties( {
    role: 'img',
    ...$$props
} ) );

$: parsedClassName = parseClassName( className ) || ``;
$: parsedStyle = parseStyle( style );
$: parsedZoom = parseZoom( zoom );
$: _hostStyle = styleToString( {
    ...computeMagnifierStyle( parsedZoom ),
    ...parsedStyle,
} );
$: {
    if ( isWebComponents ) {
        hostElement = getCurrentComponent();
        hostElement.className = `${ parsedClassName } ${ parsedZoom ? `twic-z` : `` } twic-d twic-i`;
        hostElement.role = hostProps.role;
        hostElement.style = _hostStyle;
    }
}
if ( isBrowser ) {
    onMount( () => {
        if ( parsedZoom ) {
            initMagnifier( hostElement );
        }
    } );
}
</script>
{#if isWebComponents}
    {#if parsedZoom}
        <TwicMedia { ...mediaProps } class="twic-m" mediaTag="div" mode="cover"></TwicMedia>
    {/if}
    <TwicMedia { ...mediaProps } bind:state mediaTag="img" on:statechange></TwicMedia>
{:else}
<div
    bind:this={ hostElement }
    { ...hostProps }
    class = {`twic-i ${ parsedClassName } ${ parsedZoom ? `twic-z` : `` }`}
    style = { _hostStyle }
>
    {#if parsedZoom}
        <TwicMedia { ...mediaProps } class="twic-m" mediaTag="div" mode="cover"></TwicMedia>
    {/if}
    <TwicMedia { ...mediaProps } bind:state mediaTag="img" on:statechange></TwicMedia>
</div>
{/if}
