// src/react/TwicView.tsx
import React, { type ReactNode } from "react";
import { getDataAttributeName } from "../_/config";

interface ViewAttributes {
    children: ReactNode,
}

const TwicView: React.FC< ViewAttributes > = props => {
    const { children, ...restProps } = props;
    return (
        <div
            {
                ... {
                    [ getDataAttributeName( `view` ) ]: ``,
                    ...restProps,
                }
            }
        >
            { children }
        </div>
    );
};
export default TwicView;

// src/vue/TwicView.vue
<script>
import { getDataAttributeName } from '../_/config';
export default {
    "computed": {
        "viewAttributes": () => ( {
            [ getDataAttributeName( `view` ) ]: ``,
        } ),
    },
};
</script>
<template>
    <div v-bind="viewAttributes">
        <slot />
    </div>
</template>
