// src/react/TwicMedia.tsx
import "../_/style.css";
import React, { useEffect, useRef } from "react";
import {
    computeData,
    computeMediaAttributes,
    computePlaceholderStyle,
    computeStyle,
    computeWrapperClass,
    computeWrapperStyle,
} from "../_/compute";
import { Observer } from "../_/Observer";
import {
    parseAlt,
    parseAnchor,
    parseBot,
    parseFocus,
    parseIntrinsic,
    parseMode,
    parseEager,
    parsePlaceholder,
    parsePosition,
    parsePreTransform,
    parseRatio,
    parseSrc,
    parseStep,
    parseTitle,
    parseTransition,
    parseTransitionDelay,
    parseTransitionDuration,
    parseTransitionTimingFunction,
    parseMediaTag,
    parseClassName,
    parseRefit,
} from "../_/parse";
import { preComputePlaceholder } from "../_/preCompute";
import type {
    Anchor,
    Mode,
    Placeholder,
    State,
} from "../_/types";
import { validAnchors, validModes, validPlaceholders } from "../_/validate";

import { boolean, func, number, oneOf, oneOfType, string } from "./props";
import type { MediaAttributes } from "./types";

const TwicMedia: React.FC< MediaAttributes > = props => {
    const media = useRef< HTMLElement >( null );
    const observer = useRef< Observer >(
        new Observer( ( state: State ) => {
            if ( props.onStateChange ) {
                props.onStateChange( {
                    "target": media,
                    state,
                } );
            }
        } )
    ).current;
    useEffect(
        () => {
            observer.setMedia( media.current );
            return () => {
                observer.destroy();
            };
        },
        []
    );
    const alt = parseAlt( props.alt );
    const anchor = parseAnchor( props.anchor );
    const bot = parseBot( props.bot );
    const className = parseClassName( props.className );
    const eager = parseEager( props.eager );
    // eslint-disable-next-line no-shadow
    const focus = parseFocus( props.focus );
    const intrinsic = parseIntrinsic( props.intrinsic );
    const MediaTag = parseMediaTag( props.mediaTag );
    const mode = parseMode( props.mode );
    const placeholder = parsePlaceholder( props.placeholder );
    const position = parsePosition( props.position );
    const preTransform = parsePreTransform( props.preTransform );
    const ratio = parseRatio( props.ratio );
    const refit = parseRefit( props.refit );
    const src = parseSrc( props.src );
    const step = parseStep( props.step );
    const title = parseTitle( props.title );
    const transition = parseTransition( props.transition );
    const transitionDelay = parseTransitionDelay( props.transitionDelay );
    const transitionDuration = parseTransitionDuration( props.transitionDuration );
    const transitionTimingFunction = parseTransitionTimingFunction( props.transitionTimingFunction );
    const { videoOptions } = props;
    const placeholder_ = preComputePlaceholder( placeholder, src );
    return (
        <div
            suppressHydrationWarning
            className={ computeWrapperClass( className, props.src, transition ) }
            style={ computeWrapperStyle( ratio ) }
            title={ title }
        >
            <MediaTag
                suppressHydrationWarning
                ref={ media }
                style={ computeStyle(
                    anchor,
                    MediaTag,
                    mode,
                    position,
                    transitionDelay,
                    transitionDuration,
                    transitionTimingFunction
                ) }
                { ...computeData(
                    anchor,
                    bot,
                    eager,
                    focus,
                    intrinsic,
                    MediaTag,
                    mode,
                    preTransform,
                    refit,
                    src,
                    step,
                    videoOptions
                ) }
                { ...computeMediaAttributes(
                    alt,
                    props.crossOrigin,
                    props.decoding,
                    MediaTag,
                    props.referrerPolicy
                ) }
            />
            { placeholder_ && (
                <div
                    suppressHydrationWarning
                    style = {
                        computePlaceholderStyle(
                            anchor,
                            focus,
                            mode,
                            placeholder_,
                            position,
                            preTransform,
                            ratio,
                            refit,
                            src,
                            transition,
                            transitionDelay,
                            transitionDuration,
                            transitionTimingFunction,
                            videoOptions,
                            observer.setPlaceholderData
                        )
                    }
                />
            ) }
        </div>
    );
};

TwicMedia.propTypes = {
    "alt": string,
    "anchor": oneOf< Anchor >( validAnchors ),
    "bot": string,
    "className": string,
    "focus": string,
    "intrinsic": string,
    "mode": oneOf< Mode >( validModes ),
    "eager": oneOfType( [ boolean, string ] ),
    "onStateChange": func,
    "placeholder": oneOf< Placeholder >( validPlaceholders ),
    "position": string,
    "preTransform": string,
    "ratio": number,
    "src": string,
    "step": number,
    "title": string,
    "transition": oneOfType( [ boolean, string ] ),
    "transitionDelay": string,
    "transitionDuration": string,
    "transitionTimingFunction": string,
};

export default TwicMedia;

// src/vue/TwicMedia.vue
<script>
import {
    computeData,
    computeMediaAttributes,
    computePlaceholderStyle,
    computeStyle,
    computeWrapperClass,
    computeWrapperStyle,
} from "../_/compute";
import { Observer } from "../_/Observer";
import {
    parseAlt,
    parseAnchor,
    parseBot,
    parseClassName,
    parseFocus,
    parseIntrinsic,
    parseMediaTag,
    parseMode,
    parseEager,
    parsePlaceholder,
    parsePosition,
    parsePreTransform,
    parseRatio,
    parseRefit,
    parseSrc,
    parseStep,
    parseTitle,
    parseTransition,
    parseTransitionDelay,
    parseTransitionDuration,
    parseTransitionTimingFunction,
} from "../_/parse";
import { preComputePlaceholder } from "../_/preCompute";
import { rValidAnchor, rValidIntrinsic, rValidMode, rValidPlaceholder, rValidRatio } from "../_/validate";
import { booleanProp, defineStringProp, intProp, stringProp, videoOptionsProp } from "./props";
import { callFactory } from "./utils";

const computed = {};
const props = {};
const emits = [ `stateChange` ];

for ( const [ propName, type, parseMethod ] of [
    [ `alt`, stringProp, parseAlt ],
    [ `anchor`, defineStringProp( rValidAnchor ), parseAnchor ],
    [ `bot`, stringProp, parseBot ],
    [ `className`, stringProp, parseClassName ],
    [ `crossorigin`, stringProp, v => v ],
    [ `decoding`, stringProp, v => v ],
    [ `focus`, stringProp, parseFocus ],
    [ `intrinsic`, defineStringProp( rValidIntrinsic ), parseIntrinsic ],
    [ `mediaTag`, stringProp, parseMediaTag ],
    [ `mode`, defineStringProp( rValidMode ), parseMode ],
    [ `eager`, booleanProp( null, false ), parseEager ],
    [ `placeholder`, defineStringProp( rValidPlaceholder ), parsePlaceholder ],
    [ `position`, stringProp, parsePosition ],
    [ `preTransform`, stringProp, parsePreTransform ],
    [ `ratio`, defineStringProp( rValidRatio ), parseRatio ],
    [ `referrerpolicy`, stringProp, v => v ],
    [ `refit`, booleanProp( null, false ), parseRefit ],
    [ `src`, stringProp, parseSrc ],
    [ `step`, intProp, parseStep ],
    [ `title`, stringProp, parseTitle ],
    [ `transition`, booleanProp( null, true ), parseTransition ],
    [ `transitionDelay`, stringProp, parseTransitionDelay ],
    [ `transitionDuration`, stringProp, parseTransitionDuration ],
    [ `transitionTimingFunction`, stringProp, parseTransitionTimingFunction ],
    [ `videoOptions`, videoOptionsProp, v => v ],
] ) {
    computed[ `p_${ propName }` ] = callFactory( parseMethod, [ `*${ propName }*` ] );
    props[ propName ] = type;
}
computed[ `p_undefined` ] = () => undefined;

for ( const [ propName, func, args ] of [
    [
        `_dataAttributes`,
        computeData,
        [
            `anchor`,
            `bot`,
            `eager`,
            `focus`,
            `intrinsic`,
            `mediaTag`,
            `mode`,
            `preTransform`,
            `refit`,
            `src`,
            `step`,
            `videoOptions`,
        ],
    ],
    [
        `_mediaAttributes`,
        computeMediaAttributes,
        [ [ `alt`, `crossorigin`, `decoding`, `mediaTag`, `referrerpolicy` ] ],
    ],
    [
        `_style`,
        computeStyle,
        [
            `anchor`,
            `mediaTag`,
            `mode`,
            `position`,
            `transitionDelay`,
            `transitionDuration`,
            `transitionTimingFunction`,
        ],
    ],
    [
        `_placeholderStyle`,
        computePlaceholderStyle,
        [
            `anchor`,
            `focus`,
            `mode`,
            `placeholder_`,
            `position`,
            `preTransform`,
            `ratio`,
            `refit`,
            `src`,
            `transition`,
            `transitionDelay`,
            `transitionDuration`,
            `transitionTimingFunction`,
            `videoOptions`,
            c => c.observer.setPlaceholderData,
        ],
    ],
    [
        `p_placeholder_`,
        preComputePlaceholder,
        [
            `placeholder`,
            `src`,
        ],
    ],
    [ `_wrapperClass`, computeWrapperClass, [ `className`, `src`, `transition` ] ],
    [ `_wrapperStyle`, computeWrapperStyle, [ `ratio` ] ],
] ) {
    computed[ propName ] = callFactory( func, args );
}

export default {
    "inheritAttrs": false,
    props,
    emits,
    computed,
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    beforeCreate() {
        this.observer = new Observer( state => {
            this.$emit( `stateChange`, {
                state,
            } );
        } );
    },
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    mounted() {
        this.observer.setMedia( this.$refs.media );
    },
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    unmounted() {
        this.observer.destroy();
    },
};
</script>
<template>
    <div
        :class="_wrapperClass"
        :style="_wrapperStyle"
        :title="p_title"
    >
        <component
            :is="p_mediaTag"
            ref="media"
            :style="_style"
            v-bind="{
                ..._dataAttributes,
                ..._mediaAttributes
            }"
        />
        <div
            v-if="p_placeholder_"
            :style="_placeholderStyle"
        />
    </div>
</template>
<style src="../_/style.css"></style>
