// src/react/TwicBackground.tsx
import React from "react";
import { computeHostAttributes } from "../_/compute";
import { parseClassName, parseDraggable, parseId, parseTabIndex } from "../_/parse";
import TwicMedia from "./TwicMedia";
import type { BaseAttributes } from "./types";
import { propType, string } from "./props";
import { sanitize } from "../_/utils";
import { rValidId } from "../_/validate";

interface BackgroundAttributes extends BaseAttributes {
    mediaTag?: string,
}
const defaultProps = {
    "mediaTag": `div`,
};

const TwicBackground: React.FC< BackgroundAttributes > = props => {

    const { className, draggable, id, tabindex, ...mediaAttributes } = {
        ...defaultProps,
        ...props,
    };
    const parsedClassName = parseClassName( className ) || ``;
    const parsedDraggable = parseDraggable( draggable );
    const parsedId = parseId( id );
    const parsedTabIndex = parseTabIndex( tabindex );
    return (
        <div
            className={ sanitize( `twic-i ${ parsedClassName }` ) }
            { ...computeHostAttributes(
                parsedDraggable,
                parsedId,
                parsedTabIndex
            ) }
        >
            <TwicMedia { ...mediaAttributes } className="" />
        </div>
    );
};

TwicBackground.propTypes = {
    "id": propType( `string`, rValidId ),
    "mediaTag": string,
};

export default TwicBackground;

// src/vue/TwicBackground.vue
<script>
import { computeHostAttributes } from "../_/compute";
import { parseDraggable, parseId, parseTabIndex } from "../_/parse";
import { rValidId } from "../_/validate";
import TwicMedia from "./TwicMedia.vue";
import { booleanProp, defineStringProp, intProp } from "./props";
import { callFactory } from "./utils";
const emits = [ `stateChange` ];
const props = {
    "mediaTag": defineStringProp( undefined, `div` ),
};
const computed = {};
for (
    const [ propName, type, parseMethod ] of [
        [ `draggable`, booleanProp( null, undefined ), parseDraggable ],
        [ `id`, defineStringProp( rValidId ), parseId ],
        [ `tabindex`, intProp, parseTabIndex ],
    ]
) {
    computed[ `p_${ propName }` ] = callFactory( parseMethod, [ `*${ propName }*` ] );
    props[ propName ] = type;
}

for ( const [ propName, func, args ] of [
    [
        `_hostAttributes`,
        computeHostAttributes, [ `draggable`, `id`, `tabindex` ],
    ],
]
) {
    computed[ propName ] = callFactory( func, args );
}

export default {
    "components": {
        TwicMedia,
    },
    props,
    emits,
    computed,
    "methods": {
        // eslint-disable-next-line no-shadow
        handleStateChange( event ) {
            const { state } = event;
            this.$emit( `stateChange`, {
                "target": this,
                state,
            } );
        },
    },
};
</script>
<template>
    <div
        class="twic-i"
        v-bind="{ ..._hostAttributes }"
    >
        <TwicMedia
            :media-tag="mediaTag"
            v-bind="{
                ...$attrs,
                class: ``,
            }"
            @stateChange="handleStateChange"
        />
    </div>
</template>
