// src/svelte3/img-video.svelte
<svelte:options tag={null}/>

<script context="module" lang="ts">
import type { Anchor, Attributes as BaseAttributes, Media, Mode, Placeholder, State } from "../_/types";

import {
    computeAlt,
    computeData,
    computePlaceholderStyle,
    computeStyle,
    computeWrapperClass,
    computeWrapperStyle,
} from "../_/compute";
import { isBrowser, isWebComponents } from "../_/utils";
import { createEventDispatcher, onDestroy, onMount } from "svelte/internal";
import {
    parseAlt,
    parseAnchor,
    parseBot,
    parseClassName,
    parseFocus,
    parseIntrinsic,
    parseMode,
    parseEager,
    parsePlaceholder,
    parsePosition,
    parsePreTransform,
    parseRatio,
    parseSrc,
    parseStep,
    parseTransition,
    parseTransitionDelay,
    parseTransitionDuration,
    parseTransitionTimingFunction,
} from "../_/parse";
import { styleToString } from "./utils";
import { Observer } from "../_/Observer";

export interface Attributes extends BaseAttributes {
    class?: string,
    state?: State
}

declare const MEDIA_TAG: string;
</script>
<script lang="ts">
export let alt: string = undefined;
export let anchor: Anchor = undefined;
export let bot: string = undefined;
let className: string = undefined;
export { className as class };
export let focus: string = undefined;
export let intrinsic: string = undefined;
export let mode: Mode = undefined;
export let eager: boolean = false;
export let placeholder: Placeholder = undefined;
export let position: string = undefined;
export let preTransform: string = undefined;
export let ratio: number | string = undefined;
export let src: string;
export let step: number = undefined;
export let state: State = undefined;
export let transition: boolean | string = undefined;
export let transitionDelay: string = undefined;
export let transitionDuration: string = undefined;
export let transitionTimingFunction: string = undefined;

let media: Media;

const observer = new Observer( ( _state: State )=> {
    state = _state;
}  );

const stateDispatcher = createEventDispatcher();
$: stateDispatcher( `statechange`, { state } );

$: isVideo = MEDIA_TAG === `video`;

$: parsedAlt = parseAlt( alt );
$: parsedAnchor = parseAnchor( anchor );
$: parsedBot = parseBot( bot );
$: parsedEager = parseEager( eager );
$: parsedFocus = parseFocus( focus );
$: parsedIntrinsic = parseIntrinsic( intrinsic );
$: parsedMode = parseMode( mode );
$: parsedPlaceholder = parsePlaceholder( placeholder, src );
$: parsedPosition = parsePosition( position );
$: parsedPreTransform = parsePreTransform( preTransform );
$: parsedRatio = parseRatio( ratio );
$: parsedSrc = parseSrc( src );
$: parsedStep = parseStep( step );
$: parsedTransition = parseTransition( transition );
$: parsedTransitionDelay = parseTransitionDelay( transitionDelay );
$: parsedTransitionDuration = parseTransitionDuration( transitionDuration );
$: parsedTransitionTimingFunction = parseTransitionTimingFunction( transitionTimingFunction );

$: _alt = ( isVideo ? undefined : computeAlt( parsedAlt, parsedSrc ) );
$: _data = computeData(
    parsedAnchor,
    parsedBot,
    parsedEager,
    parsedFocus,
    parsedIntrinsic,
    isVideo,
    parsedMode,
    parsedPreTransform,
    parsedSrc,
    parsedStep,
);
$: _placeholderStyle = styleToString( computePlaceholderStyle(
    parsedAnchor,
    parsedFocus,
    parsedMode,
    parsedPlaceholder,
    parsedPosition,
    parsedPreTransform,
    parsedRatio,
    parsedSrc,
    parsedTransition,
    parsedTransitionDelay,
    parsedTransitionDuration,
    parsedTransitionTimingFunction,
    observer.setPlaceholderData,
) );

$: _style = styleToString( computeStyle(
    parsedAnchor,
    parsedMode,
    parsedPosition,
    parsedTransitionDelay,
    parsedTransitionDuration,
    parsedTransitionTimingFunction
) );
$: _wrapperStyle = styleToString( computeWrapperStyle( parsedRatio ) );

// this happens BEFORE onMount
$: isWebComponents && media && ( media.parentElement.parentElement.className += ` twic-d twic-i ` );

if ( isBrowser ) {
    onMount( () => {
        observer.setMedia( media );
    } );
    onDestroy( () => {
        observer.destroy();
    } );
}
</script>

{#if isWebComponents}
<div
    class = { computeWrapperClass( src, parsedTransition ) }
    style = { _wrapperStyle }
>
    <img
        bind:this = { media }
        alt = { _alt }
        style = { _style }
        { ..._data }
    />
    <div style = "{ _placeholderStyle }" />
</div>
{:else}
<div class = {`twic-i ${ parseClassName( className ) || `` }`}>
    <div
        class = { computeWrapperClass( src, parsedTransition ) }
        style = { _wrapperStyle }
    >
        <img
            bind:this = { media }
            alt = { _alt }
            style = { _style }
            { ..._data }
        />
        <div style = "{ _placeholderStyle }" />
    </div>
</div>
{/if}

// src/react/img-video.tsx
/* eslint-disable max-lines */
import "../_/style.css";

import type {
    Anchor,
    Attributes as BaseAttributes,
    Media,
    Mode,
    Placeholder,
    State,
    StateEvent,
} from "../_/types";
import {
    computeAlt,
    computeData,
    computePlaceholderStyle,
    computeStyle,
    computeWrapperClass,
    computeWrapperStyle,
} from "../_/compute";
import {
    parseAlt,
    parseAnchor,
    parseBot,
    parseClassName,
    parseFocus,
    parseIntrinsic,
    parseMode,
    parseEager,
    parsePlaceholder,
    parsePosition,
    parsePreTransform,
    parseRatio,
    parseSrc,
    parseStep,
    parseTransition,
    parseTransitionDelay,
    parseTransitionDuration,
    parseTransitionTimingFunction,
} from "../_/parse";

// eslint-disable-next-line no-use-before-define
import React from "react";
import PropTypes from "prop-types";
import { Observer } from "../_/Observer";
import { validAnchors, validModes, validPlaceholders } from "../_/validate";

type onStateChangeType = ( stateEvent: StateEvent ) => void;

export interface Attributes extends BaseAttributes {
    className?: string,
    onStateChange?: onStateChangeType,
}

const defaultProps: Attributes = {
    "alt": undefined,
    "anchor": undefined,
    "bot": undefined,
    "className": undefined,
    "focus": undefined,
    "intrinsic": undefined,
    "mode": undefined,
    "eager": undefined,
    "onStateChange": undefined,
    "placeholder": undefined,
    "position": undefined,
    "preTransform": undefined,
    "ratio": undefined,
    "src": undefined,
    "step": undefined,
    "transition": undefined,
    "transitionDelay": undefined,
    "transitionDuration": undefined,
    "transitionTimingFunction": undefined,
};

const { oneOf, string } = PropTypes;

const number = PropTypes.oneOfType( [ PropTypes.number, string ] );

const propTypes = {
    "alt": string,
    "anchor": oneOf< Anchor >( validAnchors ),
    "bot": string,
    "className": string,
    "focus": string,
    "intrinsic": string,
    "mode": oneOf< Mode >( validModes ),
    "eager": PropTypes.oneOfType( [
        PropTypes.bool,
        PropTypes.string,
    ] ),
    "onStateChange": PropTypes.func,
    "placeholder": oneOf< Placeholder >( validPlaceholders ),
    "position": string,
    "preTransform": string,
    "ratio": string,
    "src": string,
    "step": number,
    "transition": PropTypes.oneOfType( [
        PropTypes.bool,
        PropTypes.string,
    ] ),
    "transitionDelay": string,
    "transitionDuration": string,
    "transitionTimingFunction": string,
};

export default ( Tag: `img` | `video`, withAlt?: boolean ):
    React.ComponentType< Attributes > => {
    class Component extends React.Component< Attributes > {
        static defaultProps: Attributes;
        static propTypes: {
            alt: PropTypes.Requireable<string>;
            anchor: PropTypes.Requireable<Anchor>;
            bot: PropTypes.Requireable<string>;
            className: PropTypes.Requireable<string>;
            focus: PropTypes.Requireable<string>;
            intrinsic: PropTypes.Requireable<string>;
            mode: PropTypes.Requireable<Mode>;
            eager: PropTypes.Requireable<boolean | string>;
            onStateChange: PropTypes.Requireable<onStateChangeType>;
            placeholder: PropTypes.Requireable<Placeholder>;
            position: PropTypes.Requireable<string>;
            preTransform: PropTypes.Requireable<string>;
            ratio: PropTypes.Requireable<number | string>;
            src: PropTypes.Validator<string>;
            step: PropTypes.Requireable<number | string>;
            transition: PropTypes.Requireable<boolean | string>;
            transitionDelay: PropTypes.Requireable<string>;
            transitionDuration: PropTypes.Requireable<string>;
            transitionTimingFunction: PropTypes.Requireable<string>;
        };
        private media: React.RefObject< Media >;
        private observer: Observer;
        constructor( attributes: Attributes ) {
            super( attributes );
            this.observer = new Observer( ( state: State ) => {
                if ( this.props.onStateChange ) {
                    this.props.onStateChange(
                        {
                            "target": this,
                            state,
                        }
                    );
                }
            } );
            this.media = React.createRef();
        }
        componentDidMount() {
            this.observer.setMedia( this.media.current );
        }
        componentWillUnmount() {
            this.observer.destroy();
        }
        render() {
            const { props } = this;
            const alt = withAlt && parseAlt( props.alt );
            const anchor = parseAnchor( props.anchor );
            const bot = parseBot( props.bot );
            const className = parseClassName( props.className ) || ``;
            const eager = parseEager( props.eager );
            // eslint-disable-next-line no-shadow
            const focus = parseFocus( props.focus );
            const intrinsic = parseIntrinsic( props.intrinsic );
            const isVideo = Tag === `video`;
            const mode = parseMode( props.mode );
            const placeholder = parsePlaceholder( props.placeholder, props.src );
            const position = parsePosition( props.position );
            const preTransform = parsePreTransform( props.preTransform );
            const ratio = parseRatio( props.ratio );
            const src = parseSrc( props.src );
            const step = parseStep( props.step );
            const transition = parseTransition( props.transition );
            const transitionDelay = parseTransitionDelay( props.transitionDelay );
            const transitionDuration = parseTransitionDuration( props.transitionDuration );
            const transitionTimingFunction = parseTransitionTimingFunction( props.transitionTimingFunction );

            return (
                <div className= { `twic-i ${ className }` }>
                    <div
                        className = { computeWrapperClass( props.src, transition ) }
                        style = { computeWrapperStyle( ratio ) }
                    >
                        <Tag
                            ref={ this.media }
                            alt = { withAlt ? computeAlt( alt, src ) : undefined }
                            style = {
                                computeStyle(
                                    anchor,
                                    mode,
                                    position,
                                    transitionDelay,
                                    transitionDuration,
                                    transitionTimingFunction
                                )
                            }
                            {
                                ...computeData(
                                    anchor,
                                    bot,
                                    eager,
                                    focus,
                                    intrinsic,
                                    isVideo,
                                    mode,
                                    preTransform,
                                    src,
                                    step
                                )
                            }
                        />
                        <div
                            style = {
                                computePlaceholderStyle(
                                    anchor,
                                    focus,
                                    mode,
                                    placeholder,
                                    position,
                                    preTransform,
                                    ratio,
                                    src,
                                    transition,
                                    transitionDelay,
                                    transitionDuration,
                                    transitionTimingFunction,
                                    this.observer.setPlaceholderData
                                )
                            }
                        />
                    </div>
                </div>
            );
        }
    }
    Component.defaultProps = defaultProps;
    Component.propTypes = propTypes;
    return Component;
};
