// src/vue/TwicVideo.vue
<script>
import TwicMedia from "./TwicMedia.vue";
import { booleanProp, defineStringProp, floatProp, intProp } from "./props";
import { callFactory } from "./utils";
import {
    parseDraggable,
    parseDuration,
    parseFrom,
    parseId,
    parseTabIndex,
    parseTo,
} from "../_/parse";
import {
    preComputeVideoOptions,
} from "../_/preCompute";
import { computeHostAttributes } from "../_/compute";
import { rValidId } from "../_/validate";
const emits = [ `stateChange` ];
const props = {};
const computed = {};
for (
    const [ propName, type, parseMethod ] of
    [
        [ `draggable`, booleanProp( null, undefined ), parseDraggable ],
        [ `duration`, floatProp, parseDuration ],
        [ `from`, floatProp, parseFrom ],
        [ `id`, defineStringProp( rValidId ), parseId ],
        [ `posterFrom`, floatProp, parseFrom ],
        [ `tabIndex`, intProp, parseTabIndex ],
        [ `to`, floatProp, parseTo ],
    ]
) {
    computed[ `p_${ propName }` ] = callFactory( parseMethod, [ `*${ propName }*` ] );
    props[ propName ] = type;
}
for ( const [ propName, func, args ] of [
    [ `_hostAttributes`, computeHostAttributes, [ [ `draggable`, `id`, `tabIndex` ] ] ],
    [ `_videoOptions`, preComputeVideoOptions, [ `duration`, `from`, `posterFrom`, `to` ] ],
] ) {
    computed[ propName ] = callFactory( func, args );
}

export default {
    "components": {
        TwicMedia,
    },
    props,
    emits,
    computed,
    "methods": {
        // eslint-disable-next-line no-shadow
        handleStateChange( event ) {
            const { state } = event;
            this.$emit( `stateChange`, {
                "target": this,
                state,
            } );
        },
    },
};
</script>
<template>
    <div
        class="twic-i"
        v-bind="{ ..._hostAttributes }"
    >
        <TwicMedia
            media-tag="video"
            v-bind="{
                ...$attrs,
                class: ``,
            }"
            :refit="false"
            :video-options="_videoOptions"
            @stateChange="handleStateChange"
        />
    </div>
</template>

// src/react/TwicVideo.tsx
import React from "react";
import { parseClassName, parseDraggable, parseDuration, parseFrom, parseId, parseTabIndex, parseTo } from "../_/parse";
import { computeHostAttributes } from "../_/compute";
import { preComputeVideoOptions } from "../_/preCompute";
import { number, propType } from "./props";
import TwicMedia from "./TwicMedia";
import type { BaseAttributes } from "./types";
import type { ScriptAttributes } from "../_/types";
import { sanitize } from "../_/utils";
import { rValidId } from "../_/validate";

interface VideoAttributes extends BaseAttributes, ScriptAttributes {
    duration?: number | string,
    from?: number | string,
    posterFrom?: number | string,
    to?: number | string,
}

const TwicVideo: React.FC< VideoAttributes > = props => {
    const className = parseClassName( props.className ) || ``;
    const draggable = parseDraggable( props.draggable );
    const duration = parseDuration( props.duration );
    const from = parseFrom( props.from );
    const id = parseId( props.id );
    const posterFrom = parseFrom( props.posterFrom );
    const tabindex = parseTabIndex( props.tabindex );
    const to = parseTo( props.to );
    const videoOptions = preComputeVideoOptions( duration, from, posterFrom, to );
    return (
        <div
            className={ sanitize( `twic-i ${ className }` ) }
            { ...computeHostAttributes(
                draggable,
                id,
                tabindex
            ) }
        >
            <TwicMedia
                { ...props }
                className=""
                mediaTag="video"
                refit={ false }
                videoOptions={ videoOptions }
            />
        </div>
    );
};

TwicVideo.propTypes = {
    "duration": number,
    "from": number,
    "id": propType( `string`, rValidId ),
    "posterFrom": number,
    "to": number,
};

export default TwicVideo;
