// src/svelte3/TwicVideo.svelte
<svelte:options tag={null}/>

<script context="module" lang="ts">
import {
    computeHostAttributes,
    getCurrentComponent,
    isWebComponents,
    parseClassName,
    parseDraggable,
    parseDuration,
    parseFrom,
    parseId,
    parseTabIndex,
    parseTo,
    preComputeVideoOptions,
    sanitize,
    setAttributes,
    type Anchor,
    type Mode,
    type Placeholder,
    type State
} from "./_utils.js";
import TwicMedia from "./TwicMedia.svelte";
</script>
<script lang="ts">
export let anchor: Anchor = undefined;
export let bot: string = undefined;
let className: string = undefined;
export { className as class };
export let draggable: boolean | string = undefined;
export let duration: number | string = undefined;
export let focus: string = undefined;
export let from: number | string = undefined;
export let id: string = undefined;
export let intrinsic: string = undefined;
export let mode: Mode = undefined;
export let eager: boolean = false;
export let placeholder: Placeholder = undefined;
export let position: string = undefined;
export let posterFrom: number | string = undefined;
export let preTransform: string = undefined;
export let ratio: number | string = undefined;
export let src: string;
export let step: number | string = undefined;
export let state: State = undefined;
export let title: string = undefined;
export let tabindex: number | string = undefined;
export let to: number | string = undefined;
export let transition: boolean | string = undefined;
export let transitionDelay: string = undefined;
export let transitionDuration: string = undefined;
export let transitionTimingFunction: string = undefined;

$: parsedClassName = parseClassName( className ) || ``;
$: parsedDraggable = parseDraggable( draggable );
$: parsedDuration = parseDuration( duration );
$: parsedFrom = parseFrom( from );
$: parsedId = parseId( id );
$: parsedPosterFrom = parseFrom( posterFrom );
$: parsedTabIndex = parseTabIndex( tabindex );
$: parsedTo = parseTo( to );

$: props = {
    anchor,
    bot,
    focus,
    intrinsic,
    mode,
    eager,
    placeholder,
    position,
    preTransform,
    ratio,
    src,
    step,
    title,
    transition,
    transitionDelay,
    transitionDuration,
    transitionTimingFunction
}

$: videoOptions = preComputeVideoOptions( parsedDuration, parsedFrom, parsedPosterFrom, parsedTo);

$: {
    if ( isWebComponents ) {
        const hostElement = getCurrentComponent();
        hostElement.className = sanitize( `${ parsedClassName } twic-d twic-i` );
        setAttributes( `draggable`, parsedDraggable, hostElement  );
        setAttributes( `id`, parsedId, hostElement  );
        setAttributes( `tabindex`, parsedTabIndex, hostElement  );
    }
}
</script>
{#if isWebComponents}
<TwicMedia
    mediaTag="video"
    bind:state
    { ...props }
    { videoOptions }
    on:statechange
></TwicMedia>
{:else}
<div
    class = { sanitize( `twic-i ${ parsedClassName }` ) }
    { ...computeHostAttributes(
        parsedDraggable,
        parsedId,
        parsedTabIndex
    ) }
>
    <TwicMedia
        mediaTag="video"
        bind:state
        { ...props }
        { videoOptions }
        on:statechange
    ></TwicMedia>
</div>
{/if}

// src/react/TwicVideo.tsx
import React from "react";
import { parseClassName, parseDraggable, parseDuration, parseFrom, parseId, parseTabIndex, parseTo } from "../_/parse";
import { computeHostAttributes } from "../_/compute";
import { preComputeVideoOptions } from "../_/preCompute";
import { number, propType } from "./props";
import TwicMedia from "./TwicMedia";
import type { BaseAttributes } from "./types";
import type { ScriptAttributes } from "../_/types";
import { sanitize } from "../_/utils";
import { rValidId } from "../_/validate";

interface VideoAttributes extends BaseAttributes, ScriptAttributes {
    duration?: number | string,
    from?: number | string,
    posterFrom?: number | string,
    to?: number | string,
}

const TwicVideo: React.FC< VideoAttributes > = props => {
    const className = parseClassName( props.className ) || ``;
    const draggable = parseDraggable( props.draggable );
    const duration = parseDuration( props.duration );
    const from = parseFrom( props.from );
    const id = parseId( props.id );
    const posterFrom = parseFrom( props.posterFrom );
    const tabindex = parseTabIndex( props.tabindex );
    const to = parseTo( props.to );
    const videoOptions = preComputeVideoOptions( duration, from, posterFrom, to );
    return (
        <div
            className={ sanitize( `twic-i ${ className }` ) }
            { ...computeHostAttributes(
                draggable,
                id,
                tabindex
            ) }
        >
            <TwicMedia
                { ...props }
                className=""
                mediaTag="video"
                refit={ false }
                videoOptions={ videoOptions }
            />
        </div>
    );
};

TwicVideo.propTypes = {
    "duration": number,
    "from": number,
    "id": propType( `string`, rValidId ),
    "posterFrom": number,
    "to": number,
};

export default TwicVideo;
