// src/vue/TwicImg.vue
<script>
import { booleanProp, defineNumberProp, defineStringProp, intProp } from "./props";
import { callFactory } from "./utils";
import TwicMedia from "./TwicMedia.vue";
import { computeHostAttributes, computeHostStyle } from "../_/compute";
import initMagnifier from "../_/magnifier";
import { parseAria, parseDraggable, parseId, parseTabIndex, parseZoom } from "../_/parse";
import { rValidId, rValidZoom } from "../_/validate";
const emits = [ `stateChange` ];
const props = {};
const computed = {};
for (
    const [ propName, type, parseMethod ] of [
        [ `aria`, booleanProp( null, false ), parseAria ],
        [ `draggable`, booleanProp( null, undefined ), parseDraggable ],
        [ `id`, defineStringProp( rValidId ), parseId ],
        [ `tabindex`, intProp, parseTabIndex ],
        [ `zoom`, defineNumberProp( rValidZoom ), parseZoom ],
    ]
) {
    computed[ `p_${ propName }` ] = callFactory( parseMethod, [ `*${ propName }*` ] );
    props[ propName ] = type;
}

for ( const [ propName, func, args ] of [
    [ `_hostAttributes`, computeHostAttributes, [ [ `aria`, `draggable`, `id`, `tabindex` ] ] ],
    [ `_hostStyle`, computeHostStyle, [ [ `zoom` ] ] ],
] ) {
    computed[ propName ] = callFactory( func, args );
}

export default {
    "components": {
        TwicMedia,
    },
    props,
    emits,
    computed,
    // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
    mounted() {
        if ( this.p_zoom ) {
            initMagnifier( this.$refs.hostElement );
        }
    },
    "methods": {
        // eslint-disable-next-line no-shadow
        handleStateChange( event ) {
            const { state } = event;
            this.$emit( `stateChange`, {
                "target": this,
                state,
            } );
        },
    },
};
</script>
<template>
    <div
        ref="hostElement"
        class="twic-i"
        :class="{ 'twic-z': p_zoom }"
        :style="_hostStyle"
        v-bind="{ ..._hostAttributes }"
    >
        <TwicMedia
            v-if="p_zoom"
            media-tag="div"
            v-bind="{
                ...$attrs,
                class: `twic-m`,
                mode: `cover`,
            }"
        />
        <TwicMedia
            media-tag="img"
            v-bind="{
                ...$attrs,
                class: ``,
            }"
            @stateChange="handleStateChange"
        />
    </div>
</template>

// src/react/TwicImg.tsx
import React, { useEffect, useRef } from "react";
import { boolean, number, oneOfType, propType, string } from "./props";
import TwicMedia from "./TwicMedia";
import type { BaseAttributes } from "./types";
import { computeHostAttributes, computeHostStyle } from "../_/compute";
import initMagnifier from "../_/magnifier";
import { parseClassName, parseDraggable, parseId, parseStyle, parseTabIndex, parseZoom } from "../_/parse";
import type { ScriptAttributes } from "../_/types";
import { sanitize } from "../_/utils";
import { rValidId } from "../_/validate";

interface ImgAttributes extends BaseAttributes, ScriptAttributes {
    crossorigin?: string,
    refit?: boolean | string,
    zoom?: number | string,
}

const TwicImg: React.FC< ImgAttributes > = props => {
    const hostElement = useRef< HTMLDivElement >( null );
    useEffect(
        () => {
            if ( parseZoom( props.zoom ) ) {
                initMagnifier( hostElement.current );
            }
        },
        []
    );
    const className = parseClassName( props.className ) || ``;
    const draggable = parseDraggable( props.draggable );
    const id = parseId( props.id );
    const style = parseStyle( props.style );
    const tabindex = parseTabIndex( props.tabindex );
    const zoom = parseZoom( props.zoom );
    return (
        <div
            ref={ hostElement }
            className={ sanitize( `twic-i ${ className } ${ zoom ? `twic-z` : `` }` ) }
            { ...computeHostAttributes( {
                draggable,
                id,
                tabindex,
            } ) }
            style={ computeHostStyle( {
                style,
                zoom,
            } ) }
        >
            { zoom && (
                <TwicMedia
                    { ...props }
                    className="twic-m"
                    mediaTag="div"
                    mode="cover"
                />
            ) }
            <TwicMedia
                { ...props }
                className=""
                mediaTag="img"
            />
        </div>
    );
};

TwicImg.propTypes = {
    "id": propType( `string`, rValidId ),
    "refit": oneOfType( [ boolean, string ] ),
    "zoom": number,
};
export default TwicImg;
