// src/vue/video.vue
<script>
import { computed, props } from "./media.js";

export default {
    "name": `TwicVideo`,
    props,
    computed,
};
</script>

<template>
    <div
        :class="_wrapperClass"
        :style="_wrapperStyle"
    >
        <video
            autoplay
            loop
            muted
            :src="_src"
            :style="_style"
            :width="_width"
            :height="_height"
            v-bind="_dataAttributes"
        />
    </div>
</template>

<style src="../_/style.css"></style>

// src/react/video.jsx
import React from "react";

import "../_/style.css";
import {
    computeMediaDataBot,
    computeMediaDataFocus,
    computeMediaDataSrc,
    computeMediaDataStep,
    computeMediaHeight,
    computeMediaSource,
    computeMediaStyle,
    computeMediaWidth,
    computeWrapperClass,
    computeWrapperStyle,
} from "../_/compute.js";

const TwicVideo = attributes => (
    <div className = { computeWrapperClass( attributes ) } style = { computeWrapperStyle( attributes ) }>
        <video
            autoPlay
            loop
            muted
            src = { computeMediaSource( attributes ) }
            style = { computeMediaStyle( attributes ) }
            width = { computeMediaWidth( attributes ) }
            height = { computeMediaHeight( attributes ) }
            {
                ...computeMediaDataSrc( attributes )
            }
            {
                ...computeMediaDataFocus( attributes )
            }
            {
                ...computeMediaDataBot( attributes )
            }
            {
                ...computeMediaDataStep( attributes )
            }
        />
    </div>
);

import { defaultProps, propTypes } from "./media.js";

TwicVideo.defaultProps = defaultProps;
TwicVideo.propTypes = propTypes;

export default TwicVideo;
